apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: hyperauth
    issuer: https://hyperauth.ckcloud.org/auth/realms/tmax
    clientID: argocd
    clientSecret: f1512155-8282-451a-9e61-40b886b17deb
    requestedScopes: ["openid", "profile", "email"]
    
  
