apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls-secret
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - tmax-cloud
    - argocd-server.argocd.svc
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
