apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    kubernetes.io/ingress.class: tmax-cloud
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: tmax-cloud
  rules:
  - host: argocd.ckcloud.org # 이 {{ }} 부분을 유효한 DNS로 바꿔줘야 합니다.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server 
            port:
              number: 443
  tls:
  - hosts:
    - argocd.ckcloud.org # 이 {{ }} 부분을 유효한 DNS로 바꿔줘야 합니다.
    secretName: argocd-secret # do not change, this is provided by Argo CD
